### PR TITLE
Integrated unit testing using mockito

### PR DESCRIPTION
**Pull request by JycTheDev**

### CODE REVIEW

**Comment by Frankdroid7** [comment]
All tests passed!

I would suggest you move the tests to different files.
Geo, Autosuggest, Culture should be in different files for separations of concerns.

Arrange them in different files just like we have in the `api` folder.

**Review by Frankdroid7 — CHANGES_REQUESTED** [review]
All tests passed!

I would suggest you move the tests to different files.
Geo, Autosuggest, Culture should be in different files for separations of concerns.

Arrange them in different files just like we have in the `lib/src/api` folder.

**Comment by JycTheDev** [comment]
Not sure that's ideal considering the actual implementations are in a single file

**Comment by Frankdroid7** [comment]
> Not sure that's ideal considering the actual implementations are in a single file

If we add more methods for the APIs say Geo API and Culture API, adding the test for those additional methods will make test file bloated but having them separated means the developer knows where to go to concentrate on writing test for those methods.
It's just what I think tho'

**Review by Frankdroid7 — APPROVED** [review]

**Pull request merged**
